[package]
name = "nettle_rl"
version = "0.1.0"
authors = ["azdcf"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = "0.8.1"